version: '3'

######### Services ###################################

services:
  php:
    container_name: laravel8_php
    build: docker/php
    volumes:
      - ./server:/var/www
    depends_on:
      - mysql
      - mailhog

  nginx:
    container_name: laravel8_nginx
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./server:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  mysql:
    container_name: laravel_mysql
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_DATABASE=${DB_NAME:-Laravel8-Sample}
      - MYSQL_USER=${DB_USER:-user}
      - MYSQL_PASSWORD=${DB_PASS:-}
      - MYSQL_ROOT_PASSWORD=${DB_PASS:-password}
      - TZ=${TZ:-Asia/Tokyo}
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    volumes:
      - db-store:/var/lib/mysql
    ports:
      - ${DB_PORT:-13306}:3306

  mailhog:
    container_name: laravel8_mailhog
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025

######### Volumes ###################################

volumes:
  db-store: