version: '3'

######### Services ###################################

services:
  php:
    container_name: laravel8_php
    build: docker/php
    volumes:
      - ./server:/var/www
    depends_on:
      - postgres
      - mailhog

  nginx:
    container_name: laravel8_nginx
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./server:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  postgres:
    image: postgres:10.6
    container_name: laravel_postgres
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-Laravel8-Sample}
      - POSTGRES_USER=${POSTGRES_USER:-user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-}
      - TZ=${TZ:-Asia/Tokyo}
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
      - ./docker/postgres/sql:/docker-entrypoint-initdb.d
    ports:
      - ${DB_PORT:-5432}:5432

  mailhog:
    container_name: laravel8_mailhog
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025